# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Kaijun's Blog
subtitle: To Be A Lean Developer!
author: Kaijun Chen
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://kaijun.rocks/hexo-theme-huxblog
root: /hexo-theme-huxblog/
permalink: :year/:month/:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: Kaijun的博客 | Kaijun's Blog
header-img: img/home-bg.jpg
email: Kaijun.cn@gmail.com
description: ""
keyword: ""


# SNS settings
# RSS: false
weibo_username:     Demonbane
zhihu_username:     Demonbane
github_username:    Kaijun
twitter_username:   Demonbane_x
facebook_username:  demonbane.cn
linkedin_username:  kaijun-chen-42089354

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
disqus_username: hexo-theme-huxblog

# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "我要成为魔法师!"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Friends
friends: [
    {
        title: "Kaijun's Blog",
        href: "http://blog.kaijun.rocks"
    },{
        title: "Hux Blog",
        href: "http://huangxuan.me"
    },{
        title: "Foo",
        href: "#"
    },{
        title: "Bar",
        href: "#"
    },{
        title: "Example Friends",
        href: "#"
    },{
        title: "It helps SEO",
        href: "#"
    }
]


#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: i_dont_wanna_use_default_archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: huxblog

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/Kaijun/hexo-theme-huxblog
  branch: gh-pages
